#!/bin/sh

echo
echo ===========================================================================
echo Kahlan
echo ===========================================================================
echo

vendor/bin/kahlan --config=test/integration/kahlan-config.php --spec=test/integration
